# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Luke Morrow
email: ltmorro@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal website! I'm glad you've arrived!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ltmorro.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ltmorro

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives

whitelist:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-archives

collections:
  projects:
    output: true
    permalink: /projects/:path/
  adventures:
    output: true
    permalink: /adventures/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _projects
  - scope:
      path: ""
      type: "projects"
    values:
      layout: single
      author_profile: true
  # _adventures
  - scope:
      path: ""
      type: "adventures"
    values:
      layout: single
      author_profile: true

include: ["_pages","_data"]

author:
  name   : "Luke Morrow"
  avatar : "/assets/images/profile.png"
  location : "Clemson, SC"
  bio    : "Graduate student at Clemson University."
  email  : "ltmorro@gmail.com "# optional
  linkedin : "luke-morrow"
  github : "ltmorro"

paginate: 5 # amount of posts to show
paginate_path: /page:num/
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
