remote-theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"

title: Luke Morrow
email: luke@lukemorrow.me
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal website! I'm glad you've arrived!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lukemorrow.me" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ltmorro

# Build settings
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives

whitelist:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-archives

collections:
  projects:
    output: true
    permalink: /projects/:path/
  adventures:
    output: true
    permalink: /adventures/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _projects
  - scope:
      path: ""
      type: "projects"
    values:
      layout: single
      author_profile: true
  # _adventures
  - scope:
      path: ""
      type: "adventures"
    values:
      layout: single
      author_profile: true

include: ["_pages","_data"]

author:
  name   : "Luke Morrow"
  avatar : "/assets/images/profile.png"
  location : "Clemson, SC"
  bio    : "Graduate student at Clemson University."
  email  : "luke@lukemorrow.me"# optional
  linkedin : "luke-morrow"
  #github : "ltmorro"

paginate: 5 # amount of posts to show
paginate_path: /page:num/

#Google Analytics
google_analytics: UA-119990394-1
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
